import { ShieldAlert } from "lucide-react";

export function Disclaimer({ compact = false }: { compact?: boolean }) {
  return (
    <div className="flex gap-3 rounded-xl border border-warning/30 bg-warning-soft p-3 text-sm text-warning">
      <ShieldAlert className="mt-0.5 h-4 w-4 shrink-0" />
      <p>
        <strong>Responsible AI:</strong> Responses are generated by AI and may contain errors, bias or outdated
        information.{!compact && " Review, verify facts and apply your own judgement before acting on or sharing any output. Avoid entering confidential or personal data."}
      </p>
    </div>
  );
}
